In [9]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import time

In [10]:
url = 'https://jiji.ng/vehicles'
response = requests.get(url)
html_content = response.text
jiji_soup = BeautifulSoup(html_content, 'lxml')

In [11]:
item_collection = jiji_soup.find('div', class_ = 'masonry-column')
jiji_items = item_collection.find('div', class_ = 'masonry-item')

product_name = jiji_items.find('div', class_ = 'qa-advert-title')
product_price = jiji_items.find('div', class_ = 'qa-advert-price')
product_describe = jiji_items.find('div', 'b-list-advert-base__description-text')
product_img = jiji_items.find('img')

In [12]:
item_collection = jiji_soup.find('div', class_ = 'masonry-column')

In [13]:
url = 'https://jiji.ng/vehicles'
response = requests.get(url)
html_content = response.text
jiji_soup = BeautifulSoup(html_content, 'lxml')

data = []

item_collection = jiji_soup.find_all('div', class_ = 'masonry-column')
for items in item_collection:
    jiji_items = items.find_all('div', class_ = 'masonry-item')
    for goods in jiji_items:
        product_name = goods.find('div', class_ = 'qa-advert-title')
        Name = product_name.text.strip() if product_name else "NA"
   
        product_price = goods.find('div', class_ = 'qa-advert-price')
        Price = product_price.text.strip() if product_price else "NA"

        product_describe = goods.find('div', 'b-list-advert-base__description-text')
        Description = product_describe.text.strip() if product_describe else "NA"

        product_img = goods.find('img')
        Image_link = product_img.get('src') if product_img else "NA"

        goods_info = {
             'Item': Name,
             'Price': Price,
             'Description': Description,
             'Image_link': Image_link
        }
        


        data.append(goods_info)

In [14]:
df = pd.DataFrame(data)
df.head(3)

,Item,Price,Description,Image_link
0,08 Civic 1 Door Fancy Type,"₦ 150,000",Honda Civic coupe one door set Fancy,https://pictures-nigeria.jijistatic.net/178534...
1,Toyota Corolla 2008 to 2010 Model Front Door L...,"₦ 100,000",Toyota Corolla 2008 to 2010 model front door l...,https://pictures-nigeria.jijistatic.net/178533...
2,Semi-Trailer,"₦ 14,000,000",Working perfect\nVery neat\nNigerian used\nBuy...,https://pictures-nigeria.jijistatic.net/136639...

In [15]:
df['Brand'] = df['Item'].apply(lambda x: str(x).split(' ')[0])

In [19]:
df.to_excel('jiji_data.xlsx', index=False)

In [18]:
df.head(3)

,Item,Price,Description,Image_link,Brand
0,08 Civic 1 Door Fancy Type,"₦ 150,000",Honda Civic coupe one door set Fancy,https://pictures-nigeria.jijistatic.net/178534...,08
1,Toyota Corolla 2008 to 2010 Model Front Door L...,"₦ 100,000",Toyota Corolla 2008 to 2010 model front door l...,https://pictures-nigeria.jijistatic.net/178533...,Toyota
2,Semi-Trailer,"₦ 14,000,000",Working perfect\nVery neat\nNigerian used\nBuy...,https://pictures-nigeria.jijistatic.net/136639...,Semi-Trailer